version: "3"
services:
    webng:
        build: ./webng
        ports:
            - "5000:80"
        depends_on:
            - webapi
    webapi:
        build: ./webapi
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: microsoft/mssql-server-linux:2017-latest
        volumes:
            - "./Database:/app"
        environment:
            SA_PASSWORD: "Passw0rd"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        command: /bin/bash /app/db-start.sh ; sleep infinity
