version: "3"
services:
    webui:
        build: ./webui
        ports:
            - "5000:80"
        depends_on:
            - webapi
    webapi:
        build: ./webapi
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        build: ./Database
        environment:
            SA_PASSWORD: "Passw0rd"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
